name: kerekewere
description: A set of linting rules for clean code structure
version: 0.0.1
repository: https://github.com/dumazy/kerekewere

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  analyzer: ^5.12.0
  custom_lint_builder: ^0.4.0
